export const chapters = [
  { slug: "prologue", title: "Пролог" },
  { slug: "1", title: "Розділ 1" },
  { slug: "2", title: "Розділ 2" },
  { slug: "3", title: "Розділ 3" },
  { slug: "4", title: "Розділ 4" },
  { slug: "5", title: "Розділ 5" },
  { slug: "6", title: "Розділ 6" },
  { slug: "7", title: "Розділ 7" },
  { slug: "8", title: "Розділ 8" },
  { slug: "9", title: "Розділ 9" },
  { slug: "10", title: "Розділ 10" },
  { slug: "11", title: "Розділ 11" },
  { slug: "12", title: "Розділ 12" },
  { slug: "13", title: "Розділ 13" },
  { slug: "14", title: "Розділ 14" },
  { slug: "15", title: "Розділ 15" },
  { slug: "16", title: "Розділ 16" },
  { slug: "17", title: "Розділ 17" },
  { slug: "18", title: "Розділ 18" },
  { slug: "19", title: "Розділ 19" },
  { slug: "20", title: "Розділ 20" },
  { slug: "21", title: "Розділ 21" },
  { slug: "22", title: "Розділ 22" },
  { slug: "epilogue", title: "Епілог" },
];